// مسودات الإدخال المصدّرة من لوحة الإدارة.
//
// Hadith Platform — data model v2.0.0. Generated by tools/schema/gen.py.

import 'package:flutter/foundation.dart';

import '../../../../core/content/models/review_info.dart';
import '../../../../core/json/json_reader.dart';

/// مسودة حديث من لوحة الإدخال، تُحوَّل لاحقاً إلى HadithDailyModel بعد التوثيق.
@immutable
class HadithDraft {
  const HadithDraft({
    required this.schemaVersion,
    required this.hadithId,
    required this.number,
    required this.matn,
    required this.topNarrator,
    required this.gharib,
    required this.behavioralBenefits,
    required this.review,
  });

  /// يبني الكائن من خريطة JSON، ويرمي [JsonParseException] عند أي خلل في البنية.
  factory HadithDraft.fromJson(JsonMap json) {
    return HadithDraft(
      schemaVersion: readString(json, 'schemaVersion'),
      hadithId: readString(json, 'hadithId'),
      number: readInt(json, 'number'),
      matn: readString(json, 'matn'),
      topNarrator: readString(json, 'topNarrator'),
      gharib: readModelList(json, 'gharib', GharibDraft.fromJson),
      behavioralBenefits: readStringList(json, 'behavioralBenefits'),
      review: readModel(json, 'review', ReviewInfo.fromJson),
    );
  }

  /// إصدار المخطط.
  final String schemaVersion;

  /// المعرّف المقترح، مثل nawawi40_003.
  final String hadithId;

  /// رقم الحديث في الأربعين.
  final int number;

  /// المتن المشكول كما أُدخل حرفاً بحرف.
  final String matn;

  /// الراوي الأعلى.
  final String topNarrator;

  /// المفردات وغريب الألفاظ.
  final List<GharibDraft> gharib;

  /// الفوائد السلوكية.
  final List<String> behavioralBenefits;

  /// حالة المراجعة العلمية.
  final ReviewInfo review;

  /// يحوّل الكائن إلى خريطة JSON مطابقة للمخطط.
  JsonMap toJson() {
    return <String, dynamic>{
      'schemaVersion': schemaVersion,
      'hadithId': hadithId,
      'number': number,
      'matn': matn,
      'topNarrator': topNarrator,
      'gharib': gharib.map((GharibDraft item) => item.toJson()).toList(),
      'behavioralBenefits': List<String>.of(behavioralBenefits),
      'review': review.toJson(),
    };
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) {
      return true;
    }
    return other is HadithDraft &&
        schemaVersion == other.schemaVersion &&
        hadithId == other.hadithId &&
        number == other.number &&
        matn == other.matn &&
        topNarrator == other.topNarrator &&
        listEquals(gharib, other.gharib) &&
        listEquals(behavioralBenefits, other.behavioralBenefits) &&
        review == other.review;
  }

  @override
  int get hashCode {
    return Object.hashAll(<Object?>[
      schemaVersion,
      hadithId,
      number,
      matn,
      topNarrator,
      Object.hashAll(gharib),
      Object.hashAll(behavioralBenefits),
      review,
    ]);
  }
}

/// لفظة غريبة وبيانها في مسودة.
@immutable
class GharibDraft {
  const GharibDraft({
    required this.word,
    required this.meaning,
  });

  /// يبني الكائن من خريطة JSON، ويرمي [JsonParseException] عند أي خلل في البنية.
  factory GharibDraft.fromJson(JsonMap json) {
    return GharibDraft(
      word: readString(json, 'word'),
      meaning: readString(json, 'meaning'),
    );
  }

  /// اللفظة كما في المتن.
  final String word;

  /// البيان.
  final String meaning;

  /// يحوّل الكائن إلى خريطة JSON مطابقة للمخطط.
  JsonMap toJson() {
    return <String, dynamic>{
      'word': word,
      'meaning': meaning,
    };
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) {
      return true;
    }
    return other is GharibDraft &&
        word == other.word &&
        meaning == other.meaning;
  }

  @override
  int get hashCode {
    return Object.hashAll(<Object?>[
      word,
      meaning,
    ]);
  }
}
