// مراسي الكلمات في المتن.
//
// Hadith Platform — data model v2.0.0. Generated by tools/schema/gen.py.

import 'package:flutter/foundation.dart';

import '../../../../core/json/json_reader.dart';

/// مرساة تربط بيانات بكلمة أو أكثر من مقطع في المتن.
@immutable
class TokenAnchor {
  const TokenAnchor({
    required this.segmentId,
    required this.tokenIndex,
    required this.length,
    required this.surface,
  });

  /// يبني الكائن من خريطة JSON، ويرمي [JsonParseException] عند أي خلل في البنية.
  factory TokenAnchor.fromJson(JsonMap json) {
    return TokenAnchor(
      segmentId: readString(json, 'segmentId'),
      tokenIndex: readInt(json, 'tokenIndex'),
      length: readInt(json, 'length'),
      surface: readString(json, 'surface'),
    );
  }

  /// معرّف المقطع.
  final String segmentId;

  /// رقم أول كلمة داخل المقطع (يبدأ من صفر).
  final int tokenIndex;

  /// عدد الكلمات المشمولة.
  final int length;

  /// الكلمات كما في المتن دون علامات الترقيم، للتحقق من سلامة المرساة.
  final String surface;

  /// يحوّل الكائن إلى خريطة JSON مطابقة للمخطط.
  JsonMap toJson() {
    return <String, dynamic>{
      'segmentId': segmentId,
      'tokenIndex': tokenIndex,
      'length': length,
      'surface': surface,
    };
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) {
      return true;
    }
    return other is TokenAnchor &&
        segmentId == other.segmentId &&
        tokenIndex == other.tokenIndex &&
        length == other.length &&
        surface == other.surface;
  }

  @override
  int get hashCode {
    return Object.hashAll(<Object?>[
      segmentId,
      tokenIndex,
      length,
      surface,
    ]);
  }
}
