"""Configure the Android scaffolding generated by `flutter create` in CI.

Usage: python3 tools/android/patch_manifest.py <android_dir>

The repository does not commit the android/ folder; the APK workflow generates
it on every run. This script then adds what the app needs at runtime:

1. android.permission.INTERNET in the main manifest. Flutter's template only
   adds it to the debug/profile manifests, so release builds could not stream
   recitations from the CDN without it.
2. A network security config that allows cleartext HTTP to 127.0.0.1 and
   localhost only. just_audio serves LockCachingAudioSource through a local
   proxy on the device; every other host stays HTTPS-only.
3. The TTS_SERVICE <queries> intent so Android 11+ can find the speech engine
   used by the oral mode (narration and dilemmas only, never the matn).
4. The Arabic application label.

The script is idempotent: running it twice leaves the manifest unchanged.
"""

import os
import re
import sys

LABEL = 'منصة الحديث النبوي'
NETWORK_CONFIG = """<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
    <base-config cleartextTrafficPermitted="false" />
    <domain-config cleartextTrafficPermitted="true">
        <domain includeSubdomains="false">127.0.0.1</domain>
        <domain includeSubdomains="false">localhost</domain>
    </domain-config>
</network-security-config>
"""
TTS_INTENT = """        <intent>
            <action android:name="android.intent.action.TTS_SERVICE" />
        </intent>
"""


def patch(manifest: str) -> str:
    if 'android.permission.INTERNET' not in manifest:
        manifest = re.sub(
            r'(<manifest\b[^>]*>)',
            r'\1\n    <uses-permission android:name="android.permission.INTERNET" />',
            manifest,
            count=1,
        )
    application = re.search(r'<application\b[^>]*>', manifest)
    if application is None:
        raise SystemExit('No <application> tag in the manifest.')
    tag = application.group(0)
    new_tag = tag
    if 'android:networkSecurityConfig' not in new_tag:
        new_tag = new_tag.replace(
            '<application',
            '<application\n        android:networkSecurityConfig="@xml/network_security_config"',
            1,
        )
    if re.search(r'android:label="[^"]*"', new_tag):
        new_tag = re.sub(r'android:label="[^"]*"', 'android:label="%s"' % LABEL, new_tag, count=1)
    else:
        new_tag = new_tag.replace('<application', '<application\n        android:label="%s"' % LABEL, 1)
    manifest = manifest.replace(tag, new_tag, 1)
    if 'android.intent.action.TTS_SERVICE' not in manifest:
        if '<queries>' in manifest:
            manifest = manifest.replace('<queries>', '<queries>\n' + TTS_INTENT.rstrip('\n'), 1)
        else:
            manifest = manifest.replace(
                '</manifest>',
                '    <queries>\n' + TTS_INTENT + '    </queries>\n</manifest>',
                1,
            )
    return manifest


def main(argv: list) -> int:
    if len(argv) != 2:
        print(__doc__)
        return 2
    android = argv[1]
    path = os.path.join(android, 'app', 'src', 'main', 'AndroidManifest.xml')
    with open(path, encoding='utf-8') as handle:
        original = handle.read()
    patched = patch(original)
    if patched != original:
        with open(path, 'w', encoding='utf-8') as handle:
            handle.write(patched)
    xml_dir = os.path.join(android, 'app', 'src', 'main', 'res', 'xml')
    os.makedirs(xml_dir, exist_ok=True)
    with open(os.path.join(xml_dir, 'network_security_config.xml'), 'w', encoding='utf-8') as handle:
        handle.write(NETWORK_CONFIG)
    print('patched' if patched != original else 'already configured', path)
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv))
