// محطات رحلة السيرة ومشاهدها الثلاثة.
//
// Hadith Platform — data model v2.0.0. Generated by tools/schema/gen.py.

import 'package:flutter/foundation.dart';

import '../../../../core/content/models/review_info.dart';
import '../../../../core/content/models/source_ref.dart';
import '../../../../core/json/json_reader.dart';

/// حقبة السيرة النبوية.
enum SeerahEpoch {
  /// ما قبل البعثة.
  preMission('pre_mission'),

  /// المرحلة المكية.
  meccan('meccan'),

  /// المرحلة المدنية.
  medinan('medinan');

  const SeerahEpoch(this.wire);

  /// القيمة المخزنة في ملفات JSON.
  final String wire;

  /// يحوّل قيمة JSON إلى عنصر التعداد، ويرمي [JsonParseException] للقيم المجهولة.
  static SeerahEpoch fromWire(String value) {
    for (final SeerahEpoch candidate in SeerahEpoch.values) {
      if (candidate.wire == value) {
        return candidate;
      }
    }
    throw JsonParseException('Unknown SeerahEpoch value: "$value".');
  }
}

/// المشهد الذي يشهد له النص المصدري.
enum SeerahScene {
  /// المشهد الزماني والمكاني.
  setting('setting'),

  /// المأزق أو التحدي.
  challenge('challenge'),

  /// القرار النبوي ونتيجته.
  decision('decision');

  const SeerahScene(this.wire);

  /// القيمة المخزنة في ملفات JSON.
  final String wire;

  /// يحوّل قيمة JSON إلى عنصر التعداد، ويرمي [JsonParseException] للقيم المجهولة.
  static SeerahScene fromWire(String value) {
    for (final SeerahScene candidate in SeerahScene.values) {
      if (candidate.wire == value) {
        return candidate;
      }
    }
    throw JsonParseException('Unknown SeerahScene value: "$value".');
  }
}

/// ملف محطات رحلة السيرة النبوية.
@immutable
class SeerahDataset {
  const SeerahDataset({
    required this.schemaVersion,
    required this.id,
    required this.title,
    required this.stations,
  });

  /// يبني الكائن من خريطة JSON، ويرمي [JsonParseException] عند أي خلل في البنية.
  factory SeerahDataset.fromJson(JsonMap json) {
    return SeerahDataset(
      schemaVersion: readString(json, 'schemaVersion'),
      id: readString(json, 'id'),
      title: readString(json, 'title'),
      stations: readModelList(json, 'stations', SeerahStationModel.fromJson),
    );
  }

  /// إصدار المخطط.
  final String schemaVersion;

  /// المعرّف.
  final String id;

  /// العنوان.
  final String title;

  /// المحطات مرتبة زمنياً.
  final List<SeerahStationModel> stations;

  /// يعيد المحطة بمعرّفها، أو null إن لم توجد.
  SeerahStationModel? stationById(String stationId) {
    for (final SeerahStationModel station in stations) {
      if (station.id == stationId) {
        return station;
      }
    }
    return null;
  }

  /// المحطات مرتبة زمنياً بحقل order.
  List<SeerahStationModel> get chronological {
    final List<SeerahStationModel> result = List<SeerahStationModel>.of(stations)
      ..sort(
        (SeerahStationModel a, SeerahStationModel b) => a.order.compareTo(b.order),
      );
    return List<SeerahStationModel>.unmodifiable(result);
  }

  /// يحوّل الكائن إلى خريطة JSON مطابقة للمخطط.
  JsonMap toJson() {
    return <String, dynamic>{
      'schemaVersion': schemaVersion,
      'id': id,
      'title': title,
      'stations': stations.map((SeerahStationModel item) => item.toJson()).toList(),
    };
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) {
      return true;
    }
    return other is SeerahDataset &&
        schemaVersion == other.schemaVersion &&
        id == other.id &&
        title == other.title &&
        listEquals(stations, other.stations);
  }

  @override
  int get hashCode {
    return Object.hashAll(<Object?>[
      schemaVersion,
      id,
      title,
      Object.hashAll(stations),
    ]);
  }
}

/// محطة في رحلة السيرة بمشاهدها الثلاثة: المشهد الزماني، والمأزق، والقرار النبوي.
@immutable
class SeerahStationModel {
  const SeerahStationModel({
    required this.id,
    required this.order,
    required this.title,
    required this.epoch,
    required this.timeLabel,
    required this.place,
    required this.sceneDescription,
    required this.challenge,
    required this.propheticDecision,
    required this.evidence,
    required this.review,
  });

  /// يبني الكائن من خريطة JSON، ويرمي [JsonParseException] عند أي خلل في البنية.
  factory SeerahStationModel.fromJson(JsonMap json) {
    return SeerahStationModel(
      id: readString(json, 'id'),
      order: readInt(json, 'order'),
      title: readString(json, 'title'),
      epoch: readEnum(json, 'epoch', SeerahEpoch.fromWire),
      timeLabel: readStringOrNull(json, 'timeLabel'),
      place: readModel(json, 'place', SeerahPlace.fromJson),
      sceneDescription: readString(json, 'sceneDescription'),
      challenge: readString(json, 'challenge'),
      propheticDecision: readString(json, 'propheticDecision'),
      evidence: readModelList(json, 'evidence', SeerahEvidence.fromJson),
      review: readModel(json, 'review', ReviewInfo.fromJson),
    );
  }

  /// معرّف المحطة.
  final String id;

  /// الترتيب الزمني في الرحلة.
  final int order;

  /// عنوان الحدث.
  final String title;

  /// الحقبة.
  final SeerahEpoch epoch;

  /// وسم زمني مختصر مستخلص من الشواهد، أو null إن لم تذكره.
  final String? timeLabel;

  /// موضع المشهد على الخريطة.
  final SeerahPlace place;

  /// الوصف البصري والزماني للمشهد، مصوغاً من الشواهد وحدها.
  final String sceneDescription;

  /// المأزق أو الحدث الواقعي، مصوغاً من الشواهد وحدها.
  final String challenge;

  /// القرار النبوي ونتيجته، مصوغاً من الشواهد وحدها.
  final String propheticDecision;

  /// النصوص المصدرية الموثقة منقولة بنصها.
  final List<SeerahEvidence> evidence;

  /// حالة المراجعة العلمية.
  final ReviewInfo review;

  /// شواهد مشهد واحد بترتيبها في الملف.
  List<SeerahEvidence> evidenceFor(SeerahScene scene) {
    return List<SeerahEvidence>.unmodifiable(
      evidence.where((SeerahEvidence item) => item.scene == scene),
    );
  }

  /// يحوّل الكائن إلى خريطة JSON مطابقة للمخطط.
  JsonMap toJson() {
    return <String, dynamic>{
      'id': id,
      'order': order,
      'title': title,
      'epoch': epoch.wire,
      'timeLabel': timeLabel,
      'place': place.toJson(),
      'sceneDescription': sceneDescription,
      'challenge': challenge,
      'propheticDecision': propheticDecision,
      'evidence': evidence.map((SeerahEvidence item) => item.toJson()).toList(),
      'review': review.toJson(),
    };
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) {
      return true;
    }
    return other is SeerahStationModel &&
        id == other.id &&
        order == other.order &&
        title == other.title &&
        epoch == other.epoch &&
        timeLabel == other.timeLabel &&
        place == other.place &&
        sceneDescription == other.sceneDescription &&
        challenge == other.challenge &&
        propheticDecision == other.propheticDecision &&
        listEquals(evidence, other.evidence) &&
        review == other.review;
  }

  @override
  int get hashCode {
    return Object.hashAll(<Object?>[
      id,
      order,
      title,
      epoch,
      timeLabel,
      place,
      sceneDescription,
      challenge,
      propheticDecision,
      Object.hashAll(evidence),
      review,
    ]);
  }
}

/// موضع على الخريطة التاريخية.
@immutable
class SeerahPlace {
  const SeerahPlace({
    required this.name,
    required this.latitude,
    required this.longitude,
    required this.coordinatesApproximate,
  });

  /// يبني الكائن من خريطة JSON، ويرمي [JsonParseException] عند أي خلل في البنية.
  factory SeerahPlace.fromJson(JsonMap json) {
    return SeerahPlace(
      name: readString(json, 'name'),
      latitude: readDouble(json, 'latitude'),
      longitude: readDouble(json, 'longitude'),
      coordinatesApproximate: readBool(json, 'coordinatesApproximate'),
    );
  }

  /// اسم الموضع.
  final String name;

  /// خط العرض.
  final double latitude;

  /// خط الطول.
  final double longitude;

  /// هل الإحداثيات تقريبية.
  final bool coordinatesApproximate;

  /// يحوّل الكائن إلى خريطة JSON مطابقة للمخطط.
  JsonMap toJson() {
    return <String, dynamic>{
      'name': name,
      'latitude': latitude,
      'longitude': longitude,
      'coordinatesApproximate': coordinatesApproximate,
    };
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) {
      return true;
    }
    return other is SeerahPlace &&
        name == other.name &&
        latitude == other.latitude &&
        longitude == other.longitude &&
        coordinatesApproximate == other.coordinatesApproximate;
  }

  @override
  int get hashCode {
    return Object.hashAll(<Object?>[
      name,
      latitude,
      longitude,
      coordinatesApproximate,
    ]);
  }
}

/// شاهد مصدري لمشهد من مشاهد المحطة.
@immutable
class SeerahEvidence {
  const SeerahEvidence({
    required this.scene,
    required this.source,
  });

  /// يبني الكائن من خريطة JSON، ويرمي [JsonParseException] عند أي خلل في البنية.
  factory SeerahEvidence.fromJson(JsonMap json) {
    return SeerahEvidence(
      scene: readEnum(json, 'scene', SeerahScene.fromWire),
      source: readModel(json, 'source', SourceRef.fromJson),
    );
  }

  /// المشهد الذي يشهد له النص.
  final SeerahScene scene;

  /// المصدر والموضع ونص الشاهد حرفياً.
  final SourceRef source;

  /// يحوّل الكائن إلى خريطة JSON مطابقة للمخطط.
  JsonMap toJson() {
    return <String, dynamic>{
      'scene': scene.wire,
      'source': source.toJson(),
    };
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) {
      return true;
    }
    return other is SeerahEvidence &&
        scene == other.scene &&
        source == other.source;
  }

  @override
  int get hashCode {
    return Object.hashAll(<Object?>[
      scene,
      source,
    ]);
  }
}
