// حالة المراجعة العلمية المشتركة بين الحديث والسيرة.
//
// Hadith Platform — data model v2.0.0. Generated by tools/schema/gen.py.

import 'package:flutter/foundation.dart';

import '../../json/json_reader.dart';

/// حالة المراجعة العلمية.
enum ReviewStatus {
  /// بانتظار مراجعة متخصص.
  pendingScholarlyReview('pending_scholarly_review'),

  /// معتمد للنشر.
  approved('approved'),

  /// طُلبت تعديلات.
  changesRequested('changes_requested');

  const ReviewStatus(this.wire);

  /// القيمة المخزنة في ملفات JSON.
  final String wire;

  /// يحوّل قيمة JSON إلى عنصر التعداد، ويرمي [JsonParseException] للقيم المجهولة.
  static ReviewStatus fromWire(String value) {
    for (final ReviewStatus candidate in ReviewStatus.values) {
      if (candidate.wire == value) {
        return candidate;
      }
    }
    throw JsonParseException('Unknown ReviewStatus value: "$value".');
  }
}

/// المراجعة العلمية.
@immutable
class ReviewInfo {
  const ReviewInfo({
    required this.status,
    required this.reviewer,
    required this.reviewedAt,
    required this.notes,
  });

  /// يبني الكائن من خريطة JSON، ويرمي [JsonParseException] عند أي خلل في البنية.
  factory ReviewInfo.fromJson(JsonMap json) {
    return ReviewInfo(
      status: readEnum(json, 'status', ReviewStatus.fromWire),
      reviewer: readStringOrNull(json, 'reviewer'),
      reviewedAt: readStringOrNull(json, 'reviewedAt'),
      notes: readStringList(json, 'notes'),
    );
  }

  /// الحالة.
  final ReviewStatus status;

  /// المراجع.
  final String? reviewer;

  /// تاريخ المراجعة YYYY-MM-DD.
  final String? reviewedAt;

  /// ملاحظات مفتوحة للمراجع.
  final List<String> notes;

  /// يحوّل الكائن إلى خريطة JSON مطابقة للمخطط.
  JsonMap toJson() {
    return <String, dynamic>{
      'status': status.wire,
      'reviewer': reviewer,
      'reviewedAt': reviewedAt,
      'notes': List<String>.of(notes),
    };
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) {
      return true;
    }
    return other is ReviewInfo &&
        status == other.status &&
        reviewer == other.reviewer &&
        reviewedAt == other.reviewedAt &&
        listEquals(notes, other.notes);
  }

  @override
  int get hashCode {
    return Object.hashAll(<Object?>[
      status,
      reviewer,
      reviewedAt,
      Object.hashAll(notes),
    ]);
  }
}
