// الإحالات الموثقة إلى المصادر.
//
// Hadith Platform — data model v2.0.0. Generated by tools/schema/gen.py.

import 'package:flutter/foundation.dart';

import '../../json/json_reader.dart';

/// إحالة موثقة إلى مصدر، مع نص الشاهد حرفياً للتحقق.
@immutable
class SourceRef {
  const SourceRef({
    required this.sourceId,
    required this.locator,
    required this.quote,
  });

  /// يبني الكائن من خريطة JSON، ويرمي [JsonParseException] عند أي خلل في البنية.
  factory SourceRef.fromJson(JsonMap json) {
    return SourceRef(
      sourceId: readString(json, 'sourceId'),
      locator: readStringOrNull(json, 'locator'),
      quote: readStringOrNull(json, 'quote'),
    );
  }

  /// معرّف المصدر في فهرس المصادر.
  final String sourceId;

  /// موضع الشاهد: الجزء والصفحة أو رقم الحديث.
  final String? locator;

  /// نص الشاهد كما هو في المصدر، يُستعمل في التدقيق الآلي.
  final String? quote;

  /// يحوّل الكائن إلى خريطة JSON مطابقة للمخطط.
  JsonMap toJson() {
    return <String, dynamic>{
      'sourceId': sourceId,
      'locator': locator,
      'quote': quote,
    };
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) {
      return true;
    }
    return other is SourceRef &&
        sourceId == other.sourceId &&
        locator == other.locator &&
        quote == other.quote;
  }

  @override
  int get hashCode {
    return Object.hashAll(<Object?>[
      sourceId,
      locator,
      quote,
    ]);
  }
}
